apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ${KUBE_NAMESPACE}
  labels:
    name: app
    tier: app
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  replicas: ${DEPLOYMENT_REPLICA}
  selector:
    matchLabels:
      name: app
      tier: app
  template:
    metadata:
      labels:
        name: app
        tier: app
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
        dapr.io/enabled: "true"
        dapr.io/app-id: ${DAPR_APP_ID}
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "8080"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - app
              topologyKey: kubernetes.io/hostname
      containers:
        - name: app
          image: $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA
          args:
            - /usr/local/bin/app/run.sh
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: logistics-secrets
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
