apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/consumer-deployment.yaml

