apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  # Enable CORS globally
  enable-cors: "true"
  cors-allow-origin: "*"
  
  # Proxy settings
  proxy-connect-timeout: "600"
  proxy-send-timeout: "600"
  proxy-read-timeout: "600"
  proxy-body-size: "100m"
  
  # Buffer settings
  proxy-buffer-size: "16k"
  proxy-buffers: "4 16k"
  
  # Gzip compression
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "application/json text/css application/javascript"
  
  # Keep alive settings
  keep-alive: "75"
  keep-alive-requests: "100"
  
  # HTTP2
  use-http2: "true"
  
  # SSL settings
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
  
  # Rate limiting (optional)
  # limit-req-status-code: "429"
  # limit-conn-status-code: "429"
  
  # Custom error pages (optional)
  # custom-http-errors: "404,503"
  
  # Access log settings
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
  
  # Performance tuning
  worker-processes: "auto"
  max-worker-connections: "16384"
  
  # Client body settings
  client-header-buffer-size: "1k"
  large-client-header-buffers: "4 8k"

