# NGINX Ingress Controller Installation
# 
# For standard Kubernetes clusters, install using one of these methods:
#
# METHOD 1: Using official manifest (recommended)
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.4/deploy/static/provider/cloud/deploy.yaml
#
# METHOD 2: Using Helm
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm repo update
# helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
#
# METHOD 3: For local development (Docker Desktop, minikube)
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.4/deploy/static/provider/cloud/deploy.yaml
#
# Verify installation:
# kubectl get pods -n ingress-nginx
# kubectl get svc -n ingress-nginx
#
# For LoadBalancer access on local development:
# kubectl port-forward -n ingress-nginx service/ingress-nginx-controller 80:80 443:443
---
# Note: This file is informational only.
# Please run the kubectl apply command above to install NGINX Ingress Controller.

