apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml

commonLabels:
  app: devops-frontend
  managed-by: kustomize

