apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    name: {{ .Values.namespaces.frontend }}
    managed-by: helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
  labels:
    name: {{ .Values.namespaces.backend }}
    managed-by: helm

