apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
  - base/cert-issuer.yaml
  # Temporarily disabled - too many pods on single node
  # - base/consumer-deployment.yaml

