#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
# name: gitlab-logistics-30533267-production
# namespace: nms-india-staging
#roleRef:
# apiGroup: rbac.authorization.k8s.io
# kind: ClusterRole
# name: admin
#subjects:
# - kind: ServiceAccount
#   name: logistics-30533267-production-service-account
#   namespace: logistics-30533267-production
#
##---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: gitlab-operator-admin
rules:
 - apiGroups: ["apiextensions.k8s.io"]
   resources: ["customresourcedefinitions"]
   verbs: ["get", "patch"]
 - apiGroups: [""]
   resources: ["serviceaccounts"]
   verbs: ["get", "list"]
 - apiGroups: ["apps"]
   resources: ["deployments", "deployments/finalizers"]
   verbs: [ "get", "list", "watch", "update"]
 - apiGroups: ["apps"]
   resources: ["statefulsets", "statefulsets/finalizers"]
   verbs: [ "get", "list", "watch", "update", "create"]
 - apiGroups: [""]
   resources: ["pods", "services","services/finalizers"]
   verbs: [ "get", "list", "watch", "update", "create", "delete"]
 - apiGroups: [""]
   resources: ["configmaps"]
   verbs: [ "get", "update", "create"]
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: [ "get", "list", "watch", "update"]
 - apiGroups: ["dapr.io"]
   resources: ["components"]
   verbs: [ "get", "list", "watch", "update", "create", "patch"]
 - apiGroups: ["dapr.io"]
   resources: ["pluggablecomponents"]
   verbs: [ "get", "list", "watch"]
 - apiGroups: ["dapr.io"]
   resources: ["configurations"]
   verbs: [ "get", "list", "watch"]
 - apiGroups: ["dapr.io"]
   resources: ["subscriptions"]
   verbs: [ "get", "list", "watch", "update"]
 - apiGroups: ["dapr.io"]
   resources: ["resiliencies"]
   verbs: [ "get", "list", "watch"]
 - apiGroups: ["coordination.k8s.io"]
   resources: ["leases"]
   verbs: [ "get", "list", "watch", "update", "create", "delete"]
 - apiGroups: ["", "events.k8s.io"]
   resources: ["events"]
   verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: gitlab-admin-operator
subjects:
 - kind: ServiceAccount
   name: logistics-30533267-production-service-account
   namespace: logistics-30533267-production
roleRef:
 kind: ClusterRole
 name: gitlab-operator-admin
 apiGroup: rbac.authorization.k8s.io