# Development environment configuration

global:
  domain: localhost
  environment: development

# Backend configuration for dev
backend:
  enabled: true
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  env:
    - name: PORT
      value: "8080"
    - name: ENV
      value: "development"
    - name: LOG_LEVEL
      value: "debug"

# Frontend configuration for dev
frontend:
  enabled: true
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

# Consumers configuration for dev
consumers:
  enabled: true
  image:
    tag: consumer-latest
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  env:
    - name: ENV
      value: "development"
    - name: LOG_LEVEL
      value: "debug"
  tasks:
    - name: email-processor
      replicas: 1
    - name: data-sync
      replicas: 1
    - name: report-generator
      replicas: 1

# Ingress for dev (disabled or use local domain)
ingress:
  enabled: false

