apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob
  namespace: ${KUBE_NAMESPACE}
  labels:
    name: app
    tier: cronjob
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
      tier: cronjob
  template:
    metadata:
      labels:
        name: app
        tier: cronjob
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    spec:
      containers:
        - name: app
          image: $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA
          args:
            - /usr/local/bin/app/cronjob.sh
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: logistics-secrets
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
