version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

